### ISSUE TITLE
problem at uploading image to cloudinary and problem at creating post after usersign up to the website

### ISSUE THREAD

**Issue by am0029** [marodevv/Devto-clone#5]
problem at uploading image to cloudinary  and of course user can not sign up becasue image can not be uploaded 

i asked question in stack over flow but zero answer

can u look at this problem ?

https://stackoverflow.com/questions/74747950/what-is-cloudinary-default-url-and-cloudinary-default-publicid

no one will correct some one else source code can u see 1 month zero answer 

i am learning developing but I am sure there is problem in this source code 

and problem at creating post after user sign up to the website

**Comment by marwanm-dev** [comment]
Sorry, I think it's working..  I uploaded/edited profile images and posts nothing with that
