### ISSUE TITLE
hello. sorry i asked question again . i am really sorry . can not create post and post not showing in main page but  in your latest repository 

### ISSUE THREAD

**Issue by am0029** [marodevv/Devto-clone#8]
hello this is the latest from your repository i uploaded on github :  

    [
](https://github.com/am0029/latest-dev-to-clone.git)
at the first website not loading i have to delete this line from cliet/src/postlist/component./post.jsx   line 52 makes problem
and post page not showing at clinet/src/pages/postpage/componnets/post.jsx
`  return (
    post && (
      <Wrapper>
        {isFirstPost && (
          <Image
            onClick={() =>
              navigate(`/${post.author?.username}/${createPostUrl(post.title, post.id)}`)
            }
        I HAVE TO REMOVE THIS LINE UNTILL SITE WORK >>   src={post.image.url}
          />
        )}`

cloudinary part uploading image to cloudinary .  but the posts not showing at the first page : localhost:3000   but it is ok in mongo db and post  saved in mongo db but not showing in website  post list . do not know why 
and when u click on the post and it goes to blank page instead  . 

this is your latest repository language english that i put 2 .env file one in client and one is server

but i did not add google client id because i do not have

and when u click on the post and it goes to blank page instead  .

can u check why post created in mongo db but not showing in website and pictures all white  it means picture uplaoded to cloudinary but there is no post in website with that picture and body and title . nothing . and picture not showing at all  .

**Comment by marwanm-dev** [comment]
And I already removed half of the code for posting to cloudinary in posts.. I am really disappointed is that for free again really

**Comment by am0029** [comment]
can u say what is the link of the source code that  u removed cloudinary ?

i downloaded latest from your repository and main page does not have new post .


yes it it was my problem i  did not wanted to pay to devleoper to build  for my college . there is no good thing in github .if it was good . it was not for free . but u help me really a lot but at the end nothing the issues is too many .
really need another developer 

ok how much u want for fix this issues because it is not make sense i pay to another devloper . untill they come and see another code . that not make sense ..
say how much u want for this fixes ? and i pay to u 
i need this for my college just send me full backup 

hakimlord10@gmail.com
